name: BUILD

on:
  push:
    branches:
      - develop
      - master
      - pedrolamas/*
    tags:
      - 'v*'
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Run lint
        run: |
          pnpm run lint --no-fix

      - name: Run tests
        run: |
          pnpm run test:unit

      - name: Run circular references check
        run: |
          pnpm run circular-check

      - name: Build
        run: |
          pnpm run build

      - name: Upload fluidd.zip
        uses: actions/upload-artifact@v4
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist
